name: Préparer une émission

on:
  workflow_dispatch:
    inputs:
      collection:
        type: choice
        default: Ailleurs
        options:
        - Ailleurs
        - Bagage
        - Bureau
        - Ouïedire
        required: true
      number:
        default: "999"
        required: true
        type: string
      title:
        type: string
        default: TODO
      authors:
        type: string
        default: TODO

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: andrewthetechie/gha-cookiecutter@main
        with:
          template: ./src/skel/emission
          outputDir: ./src/public/assets/emission
          cookiecutterValues: '{
            "collection": "${{ inputs.collection }}",
            "title": "${{ inputs.title }}",
            "number": "${{ inputs.number }}",
            "authors": "${{ inputs.authors }}"
          }'
      - uses: peterjgrainger/action-create-branch@v2.2.0
        if: github.repository_owner != 'constructions-incongrues'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.collection }}-${{ inputs.number }}
      - uses: eunchurn/action-publish@v1.1.1
        if: github.repository_owner != 'constructions-incongrues'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ inputs.collection }}-${{ inputs.number }}
          USER_NAME: ${{ github.actor }}
          USER_EMAIL: ${{ github.actor }}@users.noreply.github.com
      - run: git config lfs.https://github.com/constructions-incongrues/ouiedire.git/info/lfs.locksverify false
      - run: git add src/public/assets/emission/
      - run: sudo chown -R $USER:$USER .
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Création du dossier de l'émission à partir du squelette"
          title: "[${{ inputs.collection }} #${{ inputs.number }}] ${{ inputs.title }}"
          branch: "${{ inputs.collection }}-${{ inputs.number }}"
          draft: true
          delete-branch: true
          labels: Émission,${{ inputs.collection }}
          body: |
            - [ ] Description OK ?
            - [ ] Image OK ?
            - [ ] MP3 OK ?
            - [ ] Playlist OK ?

